- package-lock.json
- package.json
- src/index.tsx
> chore: Added SSG

- package.json
> chore: Remove sourcemap

- .github/workflows/deploy.yml
> chore: add cname

- src/libs.mjs
> Capitalize Yagr in libraries list

- package-lock.json
- package.json
- scripts/prefetch-data.mjs
- src/blocks/CustomBanner/CustomBanner.tsx
- src/blocks/CustomExtendedFeatures/CustomExtendedFeatures.tsx
- src/blocks/CustomExtendedFeatures/components/FeatureItem/FeatureItem.tsx
- src/blocks/CustomHeader/CustomHeader.tsx
- src/blocks/types.ts
- src/components/App/App.tsx
- src/components/Footer/Footer.tsx
- src/components/Menu/Menu.tsx
- src/content/content.ts
- src/content/menu.ts
- src/index.tsx
- src/utils.ts
> chore: update import order

- src/content/content.ts
> First news

- src/content/content.ts
> News update

- src/content/landing.ts
Add the announcement for the UIKit 5 release.
> feat: update news

- src/content/components/uikit/index.ts
Add Loader, Skeleton and Spin components
> feat: add docs for Loader, Skeleton and Spin components

- next.config.js
- src/components/MDXRenderer/ExampleBlock/ExampleBlock.scss
- src/content/components/components/StoreBadge/index.ts
- src/content/components/components/index.ts
- src/content/components/uikit/Alert/index.ts
- src/content/components/uikit/ArrowToggle/index.ts
- src/content/components/uikit/Button/index.ts
- src/content/components/uikit/Label/index.ts
- src/content/components/uikit/Loader/index.ts
- src/content/components/uikit/Menu/MenuComponent.tsx
- src/content/components/uikit/Menu/index.ts
- src/content/components/uikit/Persona/index.ts
- src/content/components/uikit/Skeleton/index.ts
- src/content/components/uikit/Spin/index.ts
- src/content/components/uikit/index.ts
- src/content/components/utils.ts
- src/types/common.ts
- add Menu component from UIkit
- refactor structure for content/components
> feat: add docs about Menu component + refactor uikit components config file structure

- src/content/components/uikit/Progress/index.ts
- src/content/components/uikit/index.ts
https://github.com/gravity-ui/uikit/pull/952
> docs: add Progress

- src/content/components/uikit/Pagination/PaginationComponent.tsx
- src/content/components/uikit/Pagination/index.ts
- src/content/components/uikit/index.ts
> feat: docs for Pagination

- src/content/roadmap.ts
changed roadmap section on landing
> roadmap change

- src/content/components/uikit/Button/ButtonWrapper.tsx
- src/content/components/uikit/Button/index.ts
https://github.com/gravity-ui/landing/issues/141
Added startIcon, endIcon, onlyIcon for sandbox's button component
> add icon props to button component

- src/components/ClipboardArea/ClipboardArea.scss
- src/components/ClipboardArea/ClipboardArea.tsx
- src/components/ClipboardIcon/ClipboardIcon.scss
- src/components/ClipboardIcon/ClipboardIcon.tsx
- src/components/Icons/IconDialog/IconContent/IconContent.tsx
- src/components/Icons/IconDialog/UsageExample/UsageExample.tsx
- src/components/MDXRenderer/ExampleBlock/ExampleBlock.scss
- src/components/MDXRenderer/ExampleBlock/ExampleBlock.tsx
> feat: add copy to clipboard in example block

- package-lock.json
- package.json
- src/content/components/uikit/Palette/PaletteComponent.tsx
- src/content/components/uikit/Palette/index.ts
- src/content/components/uikit/index.ts
This PR can be merged only after merging this PR:
https://github.com/gravity-ui/uikit/pull/1431
> feat(Palette): added uikit palette component

- src/components/Layout/Layout.scss
- src/components/Themes/Themes.scss
> Fix sandbox z-index

- package-lock.json
- package.json
- src/content/components/navigation/HotkeysPanel/HotkeysPanelComponent.scss
- src/content/components/navigation/HotkeysPanel/HotkeysPanelComponent.tsx
- src/content/components/navigation/HotkeysPanel/constants.ts
- src/content/components/navigation/HotkeysPanel/index.ts
> feat(HotkeysPanel): add hotkeys panel docs

- src/content/components/uikit/Palette/PaletteComponent.tsx
> fix: fix Palette sandbox showcase

- src/components/Icons/Icons.tsx
Before:
https://github.com/user-attachments/assets/62382590-9e46-4cc9-8a41-06b304a4e994
After:
https://github.com/user-attachments/assets/34a2e976-2e40-4a95-970b-a7f6a36793f5
> fix: open icon modal

- src/content/landing.ts
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>
> fix: fix libraries blocks order

- src/content/landing.ts
since https://github.com/facebook/create-react-app/pull/17003
> feat: move cra setup to the last tab and add deprecation commentary

- src/components/Layout/Layout.tsx
- src/hooks/useGravityAnimation.ts
- src/styles.scss
On typing **gravity** on EN keyboard or **пкфмшен** on RU keyboard (QERTY) showing animation for all items on page
> feat(gravity-animation): add gravity animation on keydown

- src/pages/_document.tsx
Add missing prefix according to Open Graph Protocol https://ogp.me/
> Attempt to update og:images automatically

- src/components/Themes/ui/PreviewTab/MailPreview/CurrentEmail/ReplyEditor/ReplyEditor.tsx
It helps to improve visibility of text in markdown editor(Text will be shown in white color in dark theme)
> feat(preview-mail): change reply component mode to markup

- package-lock.json
- package.json
Update uikit to 7.10.0 for fixing problems in Breadcrumbs and Stepper preview
> chore: update uikit version

- src/blocks/CustomHeader/CustomHeader.scss
- src/blocks/CustomHeader/CustomHeader.tsx
- src/content/landing-rtl.ts
- src/content/landing.ts
closes https://nda.ya.ru/t/gBwqUA-N7GoiBC
> feat(CustomHeader): add badges

- next.config.js
> feat: add ASSET_PREFIX to svg publicPath to make it work on different locales

- src/styles.scss
> feat: change of main font weight
